#include "printf.h"

int		main(void)
{
	unsigned int	i = -7;
	int				d = 555;
	char			c = 'c';
	char			*s = "Here";

	ft_putstr("______________ DONE: \n\n");
//_______________________________________________________ DIGITS

		printf(			"%%i 		|%i|\n", i);
	ft_printf(			"%%i 		|%i|\n", i);
	ft_putchar('\n');
		printf(			"%%d 		|%d|\n", i);
	ft_printf(			"%%d 		|%d|\n", i);
	ft_putchar('\n');
		printf(			"%%05d 		|%05d|\n", i);
	ft_printf(			"%%05d 		|%05d|\n", i);
	ft_putchar('\n');
		printf(			"%%5d 		|%5d|\n", i);
	ft_printf(			"%%5d 		|%5d|\n", i);
	ft_putchar('\n');
		printf(			"%%.1d		|%.1d|\n", i);
	ft_printf(			"%%.1d		|%.1d|\n", i);
	ft_putchar('\n');
		printf(			"%%0.5d		|%0.5d|\n", i);
	ft_printf(			"%%0.5d		|%0.5d|\n", i);
	ft_putchar('\n');
		printf(			"%%.1d		|%.1d|\n", d);
	ft_printf(			"%%.1d		|%.1d|\n", d);
	ft_putchar('\n');
		printf(			"%%5.1d		|%5.1d|\n", i);
	ft_printf(			"%%5.1d		|%5.1d|\n", i);
	ft_putchar('\n');
		printf(			"%%*d		|%*d|\n", 4, +7);
	ft_printf(			"%%*d		|%*d|\n", 4, +7);
	ft_putchar('\n');
//_______________________________________________________ CHARS
		printf(			"%%c 		|%c|\n", c);
	ft_printf(			"%%c 		|%c|\n", c);
	ft_putchar('\n');
		printf(			"%%-4c 		|%-4c|\n", c);
	ft_printf(			"%%-4c 		|%-4c|\n", c);
	ft_putchar('\n');
		printf(			"%%*c,4		|%*c|\n", 4, c);
	ft_printf(			"%%*c,4		|%*c|\n", 4, c);
	ft_putchar('\n');
		printf(			"%%*c,-		|%*c|\n", -4, c);
	ft_printf(			"%%*c,-		|%*c|\n", -4, c);
	ft_putchar('\n');
		printf(			"%%*c,0		|%*c|\n", 0, d);
	ft_printf(			"%%*c,0		|%*c|\n", 0, d);
	ft_putchar('\n');
//_______________________________________________________ STRINGS
		printf(			"%%5s 		|%5s|\n", s);
	ft_printf(			"%%5s 		|%5s|\n", s);
	ft_putchar('\n');
		printf(			"%%-5s 		|%-5s|\n", s);
	ft_printf(			"%%-5s 		|%-5s|\n", s);
	ft_putchar('\n');
		printf(			"%%.2s		|%.2s|\n", s);
	ft_printf(			"%%.2s		|%.2s|\n", s);
	ft_putchar('\n');
		printf(			"%%*s,6		|%*s|\n", 6, s);
	ft_printf(			"%%*s,6		|%*s|\n", 6, s);
	ft_putchar('\n');
		printf(			"%%6.4s		|%6.4s|\n", s);
	ft_printf(			"%%6.4s		|%6.4s|\n", s);
	ft_putchar('\n');
		printf(			"%%*.*s		|%*.*s|\n", -5, 2, s);
	ft_printf(			"%%*.*s		|%*.*s|\n", -5, 2, s);
	ft_putchar('\n');
		printf(			"%%-6.4s 		|%-6.4s|\n", s);
	ft_printf(			"%%-6.4s		|%-6.4s|\n", s);
	ft_putchar('\n');
		printf(			"%%*s,-1 		|%*s|\n", -1, s);
	ft_printf(			"%%*s,-1 		|%*s|\n", -1, s);
	ft_putchar('\n');
		printf(			"%%*s,0 		|%*s|\n", 0, s);
	ft_printf(			"%%*s,0 		|%*s|\n", 0, s);
	ft_putchar('\n');
		printf(			"%%-*s,5 		|%-*s|\n", 5, s);
	ft_printf(			"%%-*s,5 		|%-*s|\n", 5, s);
	ft_putchar('\n');
		printf(			"%%--*s,1		|%--*s|\n", 1, s);
	ft_printf(			"%%--*s,1		|%--*s|\n", 1, s);
	ft_putchar('\n');
		printf(			"%%.*s,2		|%.*s|\n", 2, s);
	ft_printf(			"%%.*s,2 		|%.*s|\n", 2, s);
	ft_putchar('\n');
//_______________________________________________________ POINTER
		printf(			"%%p 		|%p|\n", &c);
	ft_printf(			"%%p 		|%p|\n", &c);
	ft_putchar('\n');
//_______________________________________________________ HEXA
		printf(			"%%x		|%x|\n", d);
	ft_printf(			"%%x		|%x|\n", d);
	ft_putchar('\n');
		printf(			"%%X 		|%X|\n", d);
	ft_printf(			"%%X 		|%X|\n", d);
	ft_putchar('\n');
//_______________________________________________________ UNSIGNED
		printf(			"%%u 		|%u|\n", d);
	ft_printf(			"%%u 		|%u|\n", d);
	ft_putchar('\n');
//_______________________________________________________ OCTA
		printf(			"%%o 		|%o|\n", d);
	ft_printf(			"%%o 		|%o|\n", d);
	ft_putchar('\n');

	ft_putstr("_____________________________ ULTIMATE: \n");
	
		printf(			"%% d 		|% d|\n", i);
	ft_printf(			"%% d 		|% d|\n", i);
	ft_putchar('\n');
		printf(			"%%  d 		|%  d|\n", i);
	ft_printf(			"%%  d 		|%  d|\n", i);
	ft_putchar('\n');
		printf(		"%% d, 0 		|% d|\n",  0);
	ft_printf(		"%% d, 0 		|% d|\n",  0);
	ft_putchar('\n');
		printf(		"%% -4d 		|% -4d|\n", d);
	ft_printf(		"%% -4d 		|% -4d|\n", d);
	ft_putchar('\n');
		printf(		"%%+-.1d		|%+-.1d|\n", i);
	ft_printf(		"%%+-.1d		|%+-.1d|\n", i);
	ft_putchar('\n');
		printf(		"%%+-2.d		|%+-2.d|\n", 0);
	ft_printf(		"%%+-2.d		|%+-2.d|\n", 0);
	ft_putchar('\n');
		printf(			"%%+3.d		|%+3.d|\n", 0);
	ft_printf(			"%%+3.d		|%+3.d|\n", 0);
	ft_putchar('\n');
		printf(		"%% .3d 		|% .3d|\n", 5);
	ft_printf(		"%% .3d 		|% .3d|\n", 5);
	ft_putchar('\n');
		printf(		"%% -.3d 		|% -.3d|\n", i);
	ft_printf(		"%% -.3d 		|% -.3d|\n", i);
	ft_putchar('\n');
		printf(		"%% 08.5d		|% 08.5d|\n", 0);
	ft_printf(		"%% 08.5d		|% 08.5d|\n", 0);
	ft_putchar('\n');
		printf(		"%% -5d 		|% -5d|\n", i);
	ft_printf(		"%% -5d 		|% -5d|\n", i);
	ft_putchar('\n');
	
	ft_putstr("______________________________ TO FIX: \n");
	ft_putchar('\n');
		printf(			"%%u 		|%u|\n", -7);
	ft_printf(			"%%u 		|%u|\n", -7);
	ft_putchar('\n');
		printf(			"%%.d,0		|%.d|\n", 0);
	ft_printf(			"%%.d,0		|%.d|\n", 0);
	ft_putchar('\n');
		printf(			"%%.5d		|%.5d|\n", d);
	ft_printf(			"%%.5d		|%.5d|\n", d);
	ft_putchar('\n');
		printf(			"%%.5d		|%.5d|\n", i);
	ft_printf(			"%%.5d		|%.5d|\n", i);
	ft_putchar('\n');
		printf(			"%%.5d		|%.5d|\n", 0);
	ft_printf(			"%%.5d		|%.5d|\n", 0);
	ft_putchar('\n');
		printf(			"%%.0d		|%.0d|\n", 0);
	ft_printf(			"%%.0d		|%.0d|\n", 0);
	ft_putchar('\n');
		printf(			"%%-1.d		|%-1.d|\n", 0);
	ft_printf(			"%%-1.d		|%-1.d|\n", 0);
	ft_putchar('\n');
		printf(		"%%-8.5d		|%-8.5d|\n", 0);
	ft_printf(		"%%-8.5d		|%-8.5d|\n", 0);
	ft_putchar('\n');
		printf(		"%%-8.5d		|%-8.5d|\n", -217);
	ft_printf(		"%%-8.5d		|%-8.5d|\n", -217);
	ft_putchar('\n');
		printf(		"%%-8.5d		|%-8.5d|\n", 34);
	ft_printf(		"%%-8.5d		|%-8.5d|\n", 34);
	ft_putchar('\n');
		printf(		"%%-3.3d		|%-3.3d|\n", 6983);
	ft_printf(		"%%-3.3d		|%-3.3d|\n", 6983);
	ft_putchar('\n');
		printf(		"%%-8.3d		|%-8.3d|\n", 8375);
	ft_printf(		"%%-8.3d		|%-8.5d|\n", 8375);
	ft_putchar('\n');
		printf(		"%%-8.3d		|%+-8.3d|\n", -8375);
	ft_printf(		"%%-8.3d		|%+-8.5d|\n", -8375);
	ft_putchar('\n');
		printf(		"%%08.5d		|%08.5d|\n", 0);
	ft_printf(		"%%08.5d		|%08.5d|\n", 0);
	ft_putchar('\n');
	return (0);
}
